image: autogen-docker-local.artifactory.eng.vmware.com/autogen-builder:1.7

services:
  - name: docker:18-dind

stages:
  - build
  - test

before_script:
  - go get ./...
  - go get github.com/stretchr/testify/assert

build-app:
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    - ./build-bifrost.sh -a amd64 -o linux


test-app:
  stage: test
  script:
    - go test ./...
    - go test -cover -v ./...
